[package]
name = "meilisearch-error"
version = "0.24.0"
authors = ["marin <postma.marin@protonmail.com>"]
edition = "2018"

[dependencies]
actix-http = "=3.0.0-beta.10"
serde = { version = "1.0.130", features = ["derive"] }
